### PR TITLE
Remove create var

### PR DESCRIPTION
**Pull request by jysaad**

### CODE REVIEW

**Review by lorengordon — CHANGES_REQUESTED** [review]
The terraform changes all look great, but can you please restore the top-level README.md?

**Comment by jysaad** [comment]
> The terraform changes all look great, but can you please restore the top-level README.md?

just made this change as requested

**Comment by lorengordon** [comment]
@jysaad please run `make docs/format` to update the readme, so it no longer contains the reference to the variable that was removed.

**Comment by lorengordon** [comment]
also, the top-level `versions.tf` needs to be restored

**Comment by jysaad** [comment]
> The terraform changes all look great, but can you please restore the top-level README.md?

completed this in most recent push

**Comment by lorengordon** [comment]
results of `make test`:
```
PASS
ok      terraform-aws-tardigrade-vpc-endpoints/tests    2260.173s
[terratest/test]: Completed successfully!
```

**Review by lorengordon — APPROVED** [review]

**Pull request merged**
